// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-documents.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-documents.ts
var list_documents_default = defineTool({
  name: "list_documents",
  title: "List documents",
  description: "List governed documents the signed-in user is allowed to see, newest first. Never returns file contents.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum documents to return."),
    classification: z.string().optional().describe("Optional classification filter, e.g. public, internal, confidential, restricted.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, classification }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("documents").select("id, cid, filename, classification, content_type, size_bytes, created_at, client_id").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (classification) query = query.eq("classification", classification);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-document.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_document_default = defineTool2({
  name: "get_document",
  title: "Get document metadata",
  description: "Fetch metadata for one governed document by its content id (cid). Returns metadata only, never file contents.",
  inputSchema: { cid: z2.string().trim().min(3).describe("The document content id (cid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cid }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("documents").select("id, cid, filename, classification, content_type, size_bytes, created_at, updated_at, client_id").eq("cid", cid).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No accessible document with cid ${cid}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { document: data }
    };
  }
});

// src/lib/mcp/tools/list-audit-events.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_audit_events_default = defineTool3({
  name: "list_audit_events",
  title: "List audit events",
  description: "List recent tamper-evident audit events visible to the signed-in user, newest first. Optionally filter by action or result.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(25).describe("Maximum events to return."),
    action: z3.string().optional().describe("Optional action filter, e.g. ai.assist, document.download."),
    result: z3.string().optional().describe("Optional result filter, e.g. ok, denied, error.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, action, result }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("audit_events").select("id, action, result, resource_cid, document_id, meta, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (action) query = query.eq("action", action);
    if (result) query = query.eq("result", result);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tokens.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_tokens_default = defineTool4({
  name: "list_tokens",
  title: "List ephemeral tokens",
  description: "List ephemeral access tokens visible to the signed-in user with their scope, permissions, expiry and revocation state. Token secrets are never returned.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(20).describe("Maximum tokens to return."),
    active_only: z4.boolean().default(false).describe("When true, exclude revoked tokens.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tokens").select("id, token_preview, scope_cid, document_id, permissions, expires_at, revoked, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (active_only) query = query.eq("revoked", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tokens: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool5({
  name: "list_clients",
  title: "List clients",
  description: "List client records the signed-in user is assigned to or otherwise permitted to see.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(50).describe("Maximum clients to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("clients").select("id, code, name, created_at").order("name", { ascending: true }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pqhcijtvnfxrcrxolwph";
var mcp_default = defineMcp({
  name: "project-finish-line",
  title: "Project Finish Line",
  version: "0.1.0",
  instructions: "Read-only governance tools for BankOps Copilot. Inspect governed documents, ephemeral access tokens, client assignments and the tamper-evident audit trail. All access is scoped to the signed-in user by row-level security; document contents and token secrets are never exposed.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_documents_default, get_document_default, list_tokens_default, list_clients_default, list_audit_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
